### ISSUE TITLE
REMUS - Glosario de términos dominio del problema

### ISSUE THREAD

**Issue by RukisRo** [Moffinguer/IR_PROYECT#10]
Voy a crear unos cuestionarios con palabras relacionadas con el dominio del problema, que entregaré a los miembros del grupo para que especifiquen las palabras que no conocen. Después crearé un glosario de términos del dominio del problema. 

Para rellenar el cuestionario no miréis los términos en internet, es para conocer cuales son los términos conocidos por la sociedad en general. Podéis pasar el cuestionario a otros conocidos y crear una nueva columna. 
El cuestionario está aquí: https://docs.google.com/spreadsheets/d/19j2Qe22mwmu1ZlgMgRKAriiUwRMa_7gxlfXHG09f4f4/edit#gid=0 

El glosario de términos está aquí: https://docs.google.com/document/d/1RSRmVmJokxKP_m7VEkJPF1qe7h_vttGGZt1qxdi8eAE/edit

**Comment by Moffinguer** [comment]
¿Cual es el objetivo de hacer el cuestionario de palabras?

**Comment by RukisRo** [comment]
Saber las palabras que sí son conocidas para no ponerlas en el glosario de términos

**Comment by RukisRo** [comment]
Dejo la tarea en Bloqueada hasta que rellenéis el excel

**Comment by Moffinguer** [comment]
Le he pedido a mi madre que lo rellene, cuando lo tenga, paso las respuestas a las columnas extras

**Comment by RukisRo** [comment]
genial, muchas gracias @Moffinguer

**Comment by Moffinguer** [comment]
Subido

> Le he pedido a mi madre que lo rellene, cuando lo tenga, paso las respuestas a las columnas extras

**Comment by Moffinguer** [comment]
El cuestionario de terminos necesita ayuda?
Puedo definir terminos en caso de que sean al final demasiados (que me parece que la lista es algo extensa)

**Comment by RukisRo** [comment]
En principio no hace falta, tengo un manual de pintura de donde estoy sacando las definiciones, pero no me ha dado tiempo de completarlo hoy, mañana sin falta lo termino. Gracias 😄

**Comment by RukisRo** [comment]
He terminado el glosario de términos, ¿lo podéis leer? y en caso de que alguna definición no quede clara, marcáis la palabra en rojo para añadirle una imagen. 

https://docs.google.com/document/d/1RSRmVmJokxKP_m7VEkJPF1qe7h_vttGGZt1qxdi8eAE/edit

**Comment by Moffinguer** [comment]
Estuco veneciano: Entiendo que es, pero quizás visualmente con una imagen quedaría mejor, porque lo he tenido que buscar despues de leerlo y apuntarlo
Espiches: Lo siento no he logrado siquiera visualizarlo (es un taco?, un soporte?) Tuve que buscarlo

**Comment by RukisRo** [comment]
Terminado. Creo otra tarea para añadirlo a REMUS (si se puede, lo investigo)
https://docs.google.com/document/d/1RSRmVmJokxKP_m7VEkJPF1qe7h_vttGGZt1qxdi8eAE/edit

**Comment by dangalmar** [comment]
¿Al final vas a crear una nueva tarea para añadirlo a remus?
Lo digo para dar por finalizado el issue
