### ISSUE TITLE
REMUS - Actas de reunión 1

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#11]
Pasar el borrador de la primera acta al documento de requisitos

**Comment by Moffinguer** [comment]
Esperando revisión [ff0f054](https://github.com/Moffinguer/IR_PROYECT/commit/ff0f05496c5e0ea656b21fbf4430c5bc15420810)

**Comment by Moffinguer** [comment]
Texto muy espaciado, corregir con texto menos separado?

**Comment by RukisRo** [comment]
Reviso mañana desde el PC, sería conveniente que varias personas revisaran la misma tarea, para así tener más opiniones.

**Comment by RukisRo** [comment]
Creo que deberíamos pasar estas actas al documento oficial de MADEJA si os parece bien. Y después adjuntar el pdf como indicó la profesora en clase. Adjunto plantilla aquí para seguirla como modelo: https://drive.google.com/drive/u/0/folders/1i-RmqHYqVlv9GIZ5PbgTQQV7WexX42Af

En cuanto al contenido que has puesto me parece bien

--**Tarea:** Crear un documento pdf usando la plantilla anterior (alojarlo en la carpeta del drive) y poner enlace aquí:


Te encargas tu de pasar este acta @Moffinguer ?

**Comment by Moffinguer** [comment]
Acá está subida el acta usando MADEJA, porfavor revisadla. 
Me hubiera gustado haber los puntos a tratar con puntos negros, pero no logro que salgan, si alguien puede hacerlo que lo haga, y pida revisión
https://drive.google.com/file/d/1EhFxGbbxlmXMYCAJ_8kJMmQHptrOAku-/view?usp=sharing

**Comment by dangalmar** [comment]
La primera reunión está perfectamente descrita en el acta

**Comment by RukisRo** [comment]
Cierro la issue.
