### ISSUE TITLE
REMUS - Actas de reunión 1 con el cliente

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#12]
Describir las ideas, resumen del acta de la reunión, al tener una grabación, no creo que sea oportuno hacer una transcripción, sino pasar las ideas finales que hemos extraido

**Comment by Moffinguer** [comment]
Esperando revisión [ff0f054](https://github.com/Moffinguer/IR_PROYECT/commit/ff0f05496c5e0ea656b21fbf4430c5bc15420810)

**Comment by Moffinguer** [comment]
Falta nombre del cliente

**Comment by RukisRo** [comment]
Creo que deberíamos pasar estas actas al documento oficial de MADEJA si os parece bien. Y después adjuntar el pdf como indicó la profesora en clase. Adjunto plantilla aquí para seguirla como modelo: https://drive.google.com/drive/u/0/folders/1i-RmqHYqVlv9GIZ5PbgTQQV7WexX42Af

En cuanto al contenido creo que podemos sacar un poco más de información de las grabaciones de la reunión de algunos temas importantes

--Tarea: Crear un documento pdf usando la plantilla anterior (alojarlo en la carpeta del drive) y poner enlace aquí:
https://drive.google.com/drive/u/0/folders/1hi1-tjMjIffkOqbBY-MNN448BeSme1FU


Me encargo yo de pasarlo a la plantilla de MADEJA y ampliar la información

**Comment by RukisRo** [comment]
Ya está realizada el ACTA en formato MADEJA, he añadido bastantes cosas, revisadlo cuando podáis. Lo pongo en revisión

**Comment by Moffinguer** [comment]
Yo quitaría dos cosas y cambiaría otra.
En los campos donde no procede, quitar las tablas, si van a estar vacías para que están ahí?

En el apartado donde se describen los puntos tratados, aparecen unos puntos negros por cada párrafo, eso tiene pinta de que no está bien formateado

**Comment by dangalmar** [comment]
Falta indicar que hay información que guarda en su libreta en vez de en ninguna parte. En el apartado 3 de los puntos a tener en cuenta por el cliente solo se dice lo que es visible por cada tipo de usuario, pero no lo que puede o no modificar.

**Comment by RukisRo** [comment]
¿Te refieres a este párrafo? 

------------------------------------------------------------------------------------
En cuanto a los clientes, estos principalmente son particulares, aunque también pueden ser empresas. Pertenecen principalmente a Sevilla y alrededores pero también pueden ser de otras geografías. **La información de los clientes (nombre, teléfono, dirección) es almacenada en un teléfono móvil.** 
En cuanto a los trabajadores, estos se encuentran en una bolsa y son seleccionados de forma independiente para cada trabajo según demanda. **La información de los trabajadores (nombre, teléfono, especialidad) son almacenados en un teléfono móvil.**
En cuanto a los proveedores, el cliente tiene una red de tiendas de pintura y material que le facilita los productos, haciéndole descuento en algunos de los productos más utilizados (rodillos, brochas, pinceles, cinta de carrocero, pintura blanca etc. ). **Actualmente la información sobre los proveedores (nombre de la tienda, dirección, productos con descuento) no se almacena en ningún sitio.** 
En cuanto al almacén, el cliente almacena algunos productos básicos y excedentes de trabajos anteriores. **No hay control de los productos que hay en el almacén.** 
En cuanto a las facturas y presupuestos, **se realizan a papel y se almacenan en libretas y posteriormente en cajas.** 
-----------------------------------------------------------------------------------

¿Cuáles son los datos que te refieres que guarda en la libreta?

En cuanto a modificaciones, no recuerdo que se hablara en la reunión, más bien eso lo vamos a ir decidiendo nosotros no? Reviso la grabación de todas formas.

**Comment by dangalmar** [comment]
El dijo que utilizaba la libreta para apuntar cosas pero no me acuerdo cuales. Me refiero a que hay que ponerlo.

**Comment by RukisRo** [comment]
Vale, lo añado 😁

**Comment by dangalmar** [comment]
No te olvides de poner lo segundo que he dicho. Luego lo reviso y lo pongo en done.

**Comment by RukisRo** [comment]
ya está modificado : https://drive.google.com/file/d/16ZfeNZ_tQP9PLA8DSOlXtwQoIuXOpgia/view?usp=sharing

**Comment by dangalmar** [comment]
Así ya está perfecto
