### ISSUE TITLE
Preparar plantilla general Reuniones, ACTAS

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#13]
Con este documento que prepararemos,

**Comment by Moffinguer** [comment]
Espero por aprovación:
https://docs.google.com/document/d/1Y4ndCm45fRuRK3sRv-Oc02DLAnGdtB3YgZ7C0vCZKWw/edit?usp=sharing

**Comment by dangalmar** [comment]
Aprobación se escribe con "b" de bobo. Aprobado queda.

**Comment by Moffinguer** [comment]
Okay lo paso a done
