### ISSUE TITLE
REMUS - Acta reunión 2 equipo

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#14]

**Comment by Moffinguer** [comment]
Espero revisión:
https://drive.google.com/file/d/1UrXNdr622s8IW74hIHGBALlrotR9h6QQ/view?usp=sharing

**Comment by dangalmar** [comment]
Esta bien este acta

**Comment by Moffinguer** [comment]
Cuando cierres un ticket, a parte de moverlo a DONE, dale a cerrar
