### ISSUE TITLE
REMUS - Participantes del proyecto

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#21]
Hay que averiguar como poner los nombres de los integrantes del equipo, porque se quedan unos interrogantes muy feos al principio del documento

**Comment by Moffinguer** [comment]
Resuelto en commit [8bed1dd](https://github.com/Moffinguer/IR_PROYECT/commit/8bed1dd183e441fc1fac6acea56ba8951c30d581)
Esperando validación

**Comment by dangalmar** [comment]
¿Cuál es la segunda organización?

**Comment by Moffinguer** [comment]
Nuestro grupo de laboratorio, número de equipo, nombre del profesor.
En Remus, hay una plantilla de madeja y lo ponía así

**Comment by dangalmar** [comment]
Entonces en el apartado de organización de los participantes se debería poner eso no?

**Comment by Moffinguer** [comment]
Cuando lo puse, yo marque a cada uno de nosotros como miembros de esa organización.
¿Así que debería de aparecer, ya?

**Comment by Moffinguer** [comment]
Corregido, revisar

**Comment by dangalmar** [comment]
Ya está revisado
