### ISSUE TITLE
REMUS - Objetivos del proyecto

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#22]

**Comment by Moffinguer** [comment]
Resuelto en el ticket [REMUS - Participantes del proyecto#21](https://github.com/Moffinguer/IR_PROYECT/issues/21)

**Comment by dangalmar** [comment]
Corrige algunas faltas de expresión como repertir la palabra "esto".
En la expresión "el cliente nos ha pedido que se le ayude a promocionarse" del final del párrafo está mal redactado, en su lugar hay que poner "que le ayudemos".

**Comment by Moffinguer** [comment]
No estoy de acuerdo, ya que el punto quedaría en primera y tercera persona mezclados.
Mejor como "el cliente ha solicitado que se le ayude a..."

**Comment by Moffinguer** [comment]
Arreglado en este commit:
[revisar](https://github.com/Moffinguer/IR_PROYECT/commit/683eafc4a00fa3f55448b17c461f57b29d05a1a2)

**Comment by dangalmar** [comment]
Ya
