### ISSUE TITLE
REMUS - Descripción del entorno de hardware actual

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#24]

**Comment by dangalmar** [comment]
En la expresión "Las herramientas de nuestro cliente, para gestionar su negocio, son limitadas" las comas hay que quitarlas.
La expresión "a traves" lleva acento en la e.
Lo demás está bien.

**Comment by Moffinguer** [comment]
Corregido, revisar

**Comment by dangalmar** [comment]
Has quitado solo una de las comas xd.
Ya lo corrijo yo quitando eso está perfecto.
