### ISSUE TITLE
REMUS - Descripción de actores de negocios actuales

### ISSUE THREAD

**Issue by carlos-bermejo** [Moffinguer/IR_PROYECT#28]
Ampliar textualmente la información del modelo de negocio en cuanto a los actores se refiere.

**Comment by dangalmar** [comment]
En la frase "Forma parte activa del proceso, por tanto, además de ser quien tiene la responsabilidad de aceptar el presupuesto necesario y aportar las necesidades y los problemas que la empresa debe solucionar" la expresión "por tanto" hace que la oración no tenga sentido. Quítala.
Sin contar eso, el apartado es correcto.
