### ISSUE TITLE
Establish and organice sprint times

### ISSUE THREAD

**Issue by RukisRo** [Moffinguer/IR_PROYECT#3]
Se proponen fechas para las reuniones que se harán durante el proyecto: 
Primera reunión : 29-09-22 (19:30 - 20:00)

- crear un documento de planificación (aproximada), cuando el documento sea aceptado, introducir las fechas en google calendar. 

el documento está aquí: 
https://docs.google.com/spreadsheets/d/1e3XaWC2-j_24sLVEixuPForW6jryf6Frtqt1R1j2cfg/edit?usp=sharing

Dates are proposed for the meetings that will be held during the project:
First meeting: 09-29-22 (19:30 - 20:00)

- create a planning document (approximate), when the document is accepted, enter the dates in google calendar.

**Comment by Moffinguer** [comment]
La planificación me parece correcta, salvo por las reuniones extra curriculares.
Se podría plantear para que hayan más que caigan un Viernes o Fin de Semana?

Todos tenemos horarios distintos, pero en mi caso, me vendría mejor y rendiría más si fuera así.

**Comment by RukisRo** [comment]
Me parece buena idea Fernando, quizás sería buena idea ponerlas los sábado por la mañana? En principio las voy a eliminar, para que las vayamos poniendo según nos vayan haciendo falta, en los horarios que mejor nos convenga a todos.

**Comment by RukisRo** [comment]
He modificado la R1 (preparación de la primera presentación para el sábado 1 de octubre) 
Si os va pareciendo bien la planificación a todos, podéis ponerlo por aquí y pasamos esta tarea a DONE

**Comment by RukisRo** [comment]
El sprint 2 lo veo un poco largo. Alguna idea?

**Comment by Moffinguer** [comment]
Considero que el segundo sprint puede ser algo más corto, (1 semana menos quizás?) Aunque tengamos el groso del trabajo ahí, quizás no es necesario y en el tercer sprint, añadir un pelín más de tiempo, en caso de que estemos algo apurados.

**Comment by carlos-bermejo** [comment]
Yo creo que hasta que conozcamos en detalle la densidad del trabajo, lo mejor es ajustarnos a las entregas previstas. Si no, siempre podemos adaptarnos según las circunstancias, no?

**Comment by RukisRo** [comment]
vale, ahora mismo estarían ajustados a las entregas, los dejamos así y hacemos las modificaciones necesarias sobre la marcha 💃

**Comment by Moffinguer** [comment]
> Yo creo que hasta que conozcamos en detalle la densidad del trabajo, lo mejor es ajustarnos a las entregas previstas. Si no, siempre podemos adaptarnos según las circunstancias, no?

Eso también es cierto, aunque pensé que al no haber que desarrollar una aplicación entera, unos tiempos más laxos podrían ir algo mejor.

Pero esperar hasta que diga algo *22/9/2022* sería lo correcto
