### ISSUE TITLE
REMUS - Introducción al dominio del problema

### ISSUE THREAD

**Issue by pgmarc** [Moffinguer/IR_PROYECT#35]

**Comment by pgmarc** [comment]
He subido el borrador de la introducción al dominio del problema en el drive IR

**Comment by Moffinguer** [comment]
A mi me gusta, aunque ciertamente creo que hay más detalles que quizás se ¿podrían omitir?[
Adjunto referencia ](https://www.juntadeandalucia.es/servicios/madeja/contenido/libro-pautas/175#Establecer_el_dominio_del_problema)

**Comment by RukisRo** [comment]
Lo veo bastante bien

**Comment by dangalmar** [comment]
Me parece que está muy bien
