### ISSUE TITLE
First interview with client

### ISSUE THREAD

**Issue by RukisRo** [Moffinguer/IR_PROYECT#4]
A couple of persons must interview our client

- Se debe concretar un día de reunión con el cliente. 3 personas realizarán la entrevista.  1 de las 3 personas hará de secretario e irá tomando nota del desarrollo de la entrevista

- A meeting day with the client must be arranged. 3 people will carry out the interview. 1 of the 3 people will act as secretary and will take notes of the development of the interview

**Comment by Moffinguer** [comment]
Deberíamos de ponerla en revisión para analizar lo que nos ha contado?
O directamente cerrarlo?

**Comment by RukisRo** [comment]
Esta no hace falta, se puede pasar directamente a DONE. Hay que imputar el tiempo de la reunión cada uno en el Excel. 

Para revisar el tema de lo que se ha hablado, lo hacemos sobre la tarea del acta de la reunión del 29-9 y también en la reunión del sábado de la preparación de la presentación

**Comment by Moffinguer** [comment]
Okay entonces, cierro ticket
