### ISSUE TITLE
Corrección del primer entregable

### ISSUE THREAD

**Issue by RukisRo** [Moffinguer/IR_PROYECT#53]
Corregir los puntos hablados en clase

**Comment by Moffinguer** [comment]
Estos son los puntos que me quedan. Lo del zip es transversal, pero no se si alguno de ustedes ya estaba con el tema de los diagramas (separarlos para que se vean bien y/o añadirle más cosas)
Sino fuera el caso, puedo ponerme a hacer algún punto más de estos

1) ACTAS DE MADEJA, BIEN PERO EN UN ZIP, TODO A PARTE
3) CALCULAR AUTOMATICAMENTE IVA (FUNCIONALIDAD)
4) BARRA DE PROGRESO? CON O SIN SENTIDO. ¿FECHA ESTIMADA, PROGRESO DE ALGUN TIPO? INTERESANTE APORTAR ALGO ASÍ
7) REFERENCIAS? NO HAY, SERÍA IMPORTANTE PONERLAS? SI, PARA MOVERSE DE UN PUNTO A OTRO
9) PROCESOS DE NEGOCIO ACTUALES ( DIAGRAMA EN 3.2.2, ACTORES EN BASE AL DIAGRAMA)
11) CLIENTE DEBE DE PODER RECHAZAR Y ACEPTAR. EVENTO TRIGEREA OTRA COSA MARIPOSA
12) ANOTACION DE EMPLEADO ACOMPAÑA A JEFE
