### ISSUE TITLE
Create folder structure in REMUS for the first deliverable

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#7]

**Comment by Moffinguer** [comment]
Initial folder structure added at commit [45b9e06](https://github.com/Moffinguer/IR_PROYECT/commit/45b9e069a3bd06296b15d23777156bc879f11401)

For using this, replicate next steps:

1. Clone repository (if not already done)
2. Get last version of the branch
3. With [REMUS](https://github.com/amador-duran-toro/remus) installed, open file _*.rem_

**Comment by RukisRo** [comment]
Genial Fernando. Gracias

**Comment by RukisRo** [comment]
Durante la revisión se ha visto un fallo ortográfico en una de las carpetas. Si te parece bien, cuando se corrija lo avisas por aquí para que podamos descargar de nuevo el repositorio con los cambios. En el punto 2

**Comment by Moffinguer** [comment]
Arreglada errata, punto dos [682750d](https://github.com/Moffinguer/IR_PROYECT/commit/682750d4c6ada61f2f6adb37338c2a85a00ba85a)

**Comment by RukisRo** [comment]
Genial, lo paso a DONE
