### ISSUE TITLE
Rellenar acta de primera reunión

### ISSUE THREAD

**Issue by Moffinguer** [Moffinguer/IR_PROYECT#8]
Documento del acta de la reunión: https://docs.google.com/document/d/1eI6K_kRersRCC2B2ldcrlX41BOX7pOCLA3WJrh6Dpmk/edit

**Comment by Moffinguer** [comment]
Acta rellenada con la información que hemos tratado, puntos resueltos y puntos a analizar para la siguiente reunión.
A la espera de revisión

**Comment by RukisRo** [comment]
Genial Fernando, gracias. Si nadie tiene nada más que añadir, lo pasamos a DONE
