### ISSUE TITLE
Prepare WPI

### ISSUE THREAD

**Issue by RukisRo** [Moffinguer/IR_PROYECT#9]
- Se pueden preparar 2 o 3 diapositivas, donde se explique la empresa y su funcionamiento y porqué la hemos elegido. 

- 2 or 3 slides can be prepared, explaining the company and its operation and why we have chosen it.

La presentación estará aquí: https://docs.google.com/presentation/d/1EzaH5gaG9LlO0DyqJelSZzQ98lJjYnuWd1L7mxOItqU/edit#slide=id.p

**Comment by Moffinguer** [comment]
Me parece que es conciso y preciso.

El nombre de la empresa dudo que se llame Aplicaciones Povea, asumo que es una errata.

Los dos últimos puntos deberíamos de no explayarmos tanto? Quizás simplemente decir que el cliente quiere crear un sistema automatizado para el tema del contacto y la gestión del negocio? 

El cómo? No creo que sea relevante, ya que aunque el proyecto este orientado a crear un software, nunca se lo vamos a solucionar, ¿a no ser que digamos los pasos que vamos a hacer para analizar la situación y ver que le podemos ofrecer?

**Comment by RukisRo** [comment]
La empresa se llama Aplicaciones Povea, es el nombre oficial que tiene. No se refiere a aplicaciones de app, si no al tipo de aplicaciones que realiza, es un termino que se utiliza en pintura ( lo añado al glosario). 

Las dos últimas lo vemos juntos en la reunión del sábado. 

Creo que el cómo, podemos mencionarlo, simplemente por que quede bien la presentación.

**Comment by RukisRo** [comment]
Además pensar el cómo, aunque no vayamos a implementarlo, estaría bien pensarlo si tenemos en mente hacer el prototipo funcional.

**Comment by Moffinguer** [comment]
> La empresa se llama Aplicaciones Povea, es el nombre oficial que tiene. No se refiere a aplicaciones de app, si no al tipo de aplicaciones que realiza, es un termino que se utiliza en pintura ( lo añado al glosario). 
> 
> Las dos últimas lo vemos juntos en la reunión del sábado. 
> 
> Creo que el cómo, podemos mencionarlo, simplemente por que quede bien la presentación.

Okay, entonces sin ningún apunte más :)

**Comment by RukisRo** [comment]
Terminado. Finalmente las dos últimas diapositivas las he unido en una, de la otra forma era muy poco información en cada una. La presentación está pensada para tardar entre 5 y 6 minutos. Creo que con dos personas para exponer es suficiente ( PEDRO y FERNANDO) 

@pgmarc  - Diapositiva 1,2 y 3
@Moffinguer - Diapositiva 4 y 5

**Comment by Moffinguer** [comment]
Oh no qué pena.
Pues nada, haré lo mejor que pueda

**Comment by dangalmar** [comment]
La presentación a quedado genial. Antes de cerrar el issue esperaremos a que lo vean los demás y digan.

**Comment by pgmarc** [comment]
Está muy bien la presentación. Ya podeis cerrar el issue

**Comment by Moffinguer** [comment]
Salvo por la foto que faltaba, yo le había dado el visto bueno
